import esbuild from 'esbuild';
import sveltePlugin from 'esbuild-svelte';
import { sveltePreprocess } from 'svelte-preprocess';
import path from 'path';

const prod = process.argv[2] === 'production';

const banner = `/*
 * THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
 * Source: https://github.com/erayaydn0/obsidian-plugin (vault-search)
 */
`;

/** Obsidian loads main.js, manifest.json, and styles.css from the plugin folder root (same as obsidian-sample-plugin). */
const PLUGIN_ROOT = path.resolve('.');

/**
 * Stubs native addons that transformers.node.min.cjs requires at module-init time
 * but never calls during text embedding.  Without this, Electron throws
 * "Cannot find module 'sharp'" before _loadModel even starts.
 */
const nativeStubPlugin = {
  name: 'native-stub',
  setup(build) {
    const stubs = ['sharp'];
    for (const mod of stubs) {
      build.onResolve({ filter: new RegExp(`^${mod}$`) }, () => ({
        path: mod,
        namespace: 'native-stub',
      }));
    }
    build.onLoad({ filter: /.*/, namespace: 'native-stub' }, (args) => ({
      contents: `// stubbed native module: ${args.path}\nmodule.exports = {};`,
      loader: 'js',
    }));
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  loader: { '.wasm': 'binary' },
  alias: {
    // Use the Node CJS build of transformers so it runs in Electron's renderer which
    // has IS_NODE_ENV=true.  The web build's IS_NODE_ENV branch falls back to its
    // empty onnxruntime-node stub; the node build does require("onnxruntime-node")
    // which we redirect below to the pure-WASM ort bundle.
    '@huggingface/transformers':
      './node_modules/@huggingface/transformers/dist/transformers.node.min.cjs',
    // Redirect the native addon to the pure-WASM ort build so Obsidian can run it.
    'onnxruntime-node':
      './node_modules/onnxruntime-web/dist/ort.wasm.bundle.min.mjs',
    // Keep webgpu alias so any internal transformers webgpu path doesn't break.
    'onnxruntime-web/webgpu':
      './node_modules/onnxruntime-web/dist/ort.webgpu.bundle.min.mjs',
  },
  external: [
    'obsidian',
    'electron',
    '@codemirror/*',
    '@lezer/*',
    '@modelcontextprotocol/sdk',
    'zod',
  ],
  format: 'cjs',
  platform: 'node',
  target: 'es2020',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  minify: prod,
  outfile: path.join(PLUGIN_ROOT, 'main.js'),
  plugins: [
    nativeStubPlugin,
    sveltePlugin({
      preprocess: sveltePreprocess(),
      compilerOptions: { css: 'injected' },
    }),
  ],
});

if (prod) {
  await context.rebuild();
  await context.dispose();
  process.exit(0);
}

await context.watch();
